/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109863-g4113445e9d-20230215"
#endif /* AVUTIL_FFVERSION_H */
